import { test, expect } from '@playwright/test';


test('test', async ({ page }) => {
  await page.goto('https://gldev-ui.azurewebsites.net/login');
  await page.getByRole('combobox', { name: 'Role' }).click();
  await page.getByRole('option', { name: 'Cashier' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('valuerno102');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Valuerno@102');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Customer' }).click();
  await page.getByRole('link', { name: 'Customer List' }).click();
  await page.getByRole('textbox', { name: 'UCIC Number' }).click();
  await page.getByRole('radio', { name: 'Customer Details' }).click();
  await page.getByRole('textbox', { name: 'Customer Name *' }).click();
  await page.getByRole('textbox', { name: 'Customer Name *' }).fill('saurav');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('button', { name: 'View' }).first().click();
  await page.getByRole('button', { name: 'Request New Loan' }).click();
  await page.getByRole('combobox').click();
  await page.getByText('Purchase of vehicle').click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('button', { name: 'Turn Camera On' }).click();
  await page.getByRole('button', { name: 'Capture Photo' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('button', { name: 'Add Ornament' }).click();
  await page.getByRole('combobox').click();
  await page.locator('div').filter({ hasText: /^Quantity \*$/ }).click();
  await page.getByRole('spinbutton', { name: 'Quantity *' }).fill('1');
  await page.getByRole('textbox', { name: 'Gross Weight (grams) *' }).click();
  await page.getByRole('textbox', { name: 'Gross Weight (grams) *' }).fill('2');
  await page.getByRole('button', { name: 'Add Ornament' }).click();
  await page.getByRole('button', { name: 'Capture Photo' }).click();
  await page.getByRole('button', { name: 'Capture Photo' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select karat/purity' }).click();
  await page.getByText('22K').click();
  await page.getByRole('combobox').filter({ hasText: 'Select condition' }).click();
  await page.getByRole('option', { name: 'Good' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Wife' }).click();
  await page.getByRole('textbox', { name: 'Enter nominee name' }).click();
  await page.getByRole('textbox', { name: 'Enter nominee name' }).fill('test');
  await page.locator('input[type="date"]').fill('1997-01-01');
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('button', { name: 'Ornaments Details Completed' }).click();
  await page.getByRole('button', { name: 'Add Ornament' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity *' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity *' }).fill('33');
  await page.getByRole('textbox', { name: 'Gross Weight (grams) *' }).click();
  await page.getByText('Ornament Type *Select ornament typeQuantity *Gross Weight (grams) *Khimji').click();
  await page.getByRole('textbox', { name: 'Gross Weight (grams) *' }).click();
  await page.getByRole('textbox', { name: 'Gross Weight (grams) *' }).fill('3');
  await page.getByRole('button', { name: 'Add Ornament' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('spinbutton', { name: 'Quantity *' }).click();
  await page.getByRole('button', { name: 'Add Ornament' }).click();
  await page.getByRole('button', { name: 'Capture Photo' }).click();
  await page.getByRole('button', { name: 'Capture Photo' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select karat/purity' }).click();
  await page.getByText('22K').click();
  await page.getByRole('combobox').filter({ hasText: 'Select condition' }).click();
  await page.getByRole('option', { name: 'Good' }).click();
  await page.getByRole('button', { name: '2 Necklace Gross : 3g, Qty :' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select karat/purity' }).click();
  await page.getByRole('option', { name: '22K' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select condition' }).click();
  await page.getByRole('option', { name: 'Good' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.getByRole('textbox', { name: 'Enter nominee name' }).click();
  await page.getByRole('button', { name: 'Save & Continue' }).click();
  await page.locator('rect').nth(3).click();
  await page.goto('https://gldev-ui.azurewebsites.net/login');
});